### ISSUE TITLE
From zebra crossing line to traffic light position

### ISSUE THREAD

**Issue by marcoleino** [samuelyu2002/pedestrian-traffic-lights#6]
Hello,

We're working on changing the labels to get the prediction of the position of the traffic light, instead of the points for the zebra crossing prediction. We finished labeling and we have ascertained that the new coordinates are good. The new (x1,y1,x2,y2) refers to the upper-left angle of the traffic light box (p1) and the bottom-right angle of the traffic light box (p2), so that to get a bounding box.

Problem with Lytnet: the precisions of classes remain always [0.30, 0.29, 0, 0, 0], even after the 600th epoch. Do you have any suggestion to how set the coordinates to predict the position of the traffic light with Lytnet?

Thank you very much in advance

**Comment by samuelyu2002** [comment]
You might have to adjust the weighting of the MSE loss (which is for the position prediction), and the cross entropy loss (which is for the classification). The issue might be that the MSE loss is weighted too low. Otherwise, assuming that the new labels follow exactly the same form as the old labels, it should work in theory.
